spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin123!@#

rabbitmq:
  queue:
    name: hello.queue
  exchange:
    name: hello.exchange
  routing:
    key: hello.key